Daraja HTTP Framework: TdjWebComponentHolder Class Reference
TdjWebComponentHolder Class Reference
Holds a WebComponent and configuration data.
Public Member Functions
TdjWebComponentHolder (TdjWebComponentClass WebComponentClass)
Constructor.
~TdjWebComponentHolder ()
Destructor.
TdjWebComponentClass GetClass ()
IContext GetContext ()
Get the context.
TdjWebComponent GetWebComponent ()
Boolean IsStarted ()
Boolean IsStopped ()
SetContext (const IContext Context)
Set the context.
SetInitParameter (const string Key, const string Value)
Set initialization parameter.
SetStarted (const Boolean Value)
SetStopped (const Boolean Value)
Start ()
Starts the component.
Stop ()
Stops the component.
Public Attributes
TCriticalSection CS
TdjWebComponentClass FClass
IWebComponentConfig FConfig
Boolean FStopped
TdjWebComponent FWebComponent
string Name
Boolean Started
Boolean Stopped
TdjWebComponent WebComponent
The instance of the Web Component.
TdjWebComponentClass WebComponentClass
The Web Component Class.
Protected Member Functions
CheckStarted ()
Raises an exception if the lifecycle is in "started" state.
CheckStopped ()
Raises an exception if the lifecycle is in "stopped" state.
Detailed Description
Holds a WebComponent and configuration data.
Constructor & Destructor Documentation
TdjWebComponentHolder()
TdjWebComponentHolder::TdjWebComponentHolder (TdjWebComponentClass WebComponentClass)
Constructor.
Parameters
WebComponentClass the Web Component class
Referenced by GetContext(), SetContext(), and SetInitParameter().
~TdjWebComponentHolder()
TdjWebComponentHolder::~TdjWebComponentHolder ()
Destructor.
Member Function Documentation
CheckStarted()
TdjLifeCycle::CheckStarted () protected inherited
Raises an exception if the lifecycle is in "started" state.
CheckStopped()
TdjLifeCycle::CheckStopped () protected inherited
Raises an exception if the lifecycle is in "stopped" state.
References TdjLifeCycle().
GetClass()
TdjWebComponentClass TdjWebComponentHolder::GetClass ()
References WebComponentClass.
GetContext()
IContext TdjWebComponentHolder::GetContext ()
Get the context.
References TdjWebComponentHolder().
GetWebComponent()
TdjWebComponent TdjWebComponentHolder::GetWebComponent ()
IsStarted()
Boolean TdjLifeCycle::IsStarted () inherited
Returns
True if component is started
Implements ILifeCycle.
References TdjLifeCycle().
Referenced by DoStart(), and TdjWebComponentHandler::InvokeService().
IsStopped()
Boolean TdjLifeCycle::IsStopped () inherited
Returns
True if component is stopped
Implements ILifeCycle.
References Create().
Referenced by DoStart().
SetContext()
TdjWebComponentHolder::SetContext (const IContext Context)
Set the context.
Parameters
Context the context
References TdjWebComponentHolder(), and WebComponentClass.
SetInitParameter()
TdjWebComponentHolder::SetInitParameter (const string Key, const string Value)
Set initialization parameter.
Parameters
Key init parameter name
Value init parameter value
References TdjWebComponentHolder(), FClass, and WebComponentClass.
SetStarted()
TdjLifeCycle::SetStarted (const Boolean Value) inherited
Referenced by DoStop().
SetStopped()
TdjLifeCycle::SetStopped (const Boolean Value) inherited
Referenced by DoStop().
Start()
TdjLifeCycle::Start () inherited
Starts the component.
Implements ILifeCycle.
References TdjLifeCycle().
Referenced by DoStart().
Stop()
TdjLifeCycle::Stop () inherited
Stops the component.
Implements ILifeCycle.
References Stopped.
Referenced by DoStart(), and TdjWebComponentHandler::InvokeService().
Member Data Documentation
CS
TCriticalSection TdjLifeCycle::CS inherited
Referenced by ~TdjLifeCycle().
FClass
TdjWebComponentClass TdjWebComponentHolder::FClass
Referenced by SetInitParameter().
FConfig
IWebComponentConfig TdjWebComponentHolder::FConfig
FStopped
Boolean TdjLifeCycle::FStopped inherited
Referenced by ~TdjLifeCycle(), and DoStop().
FWebComponent
TdjWebComponent TdjWebComponentHolder::FWebComponent
Name
string TdjGenericHolder::Name inherited
Started
Boolean TdjLifeCycle::Started inherited
Referenced by TdjHandlerCollection::~TdjHandlerCollection(), and DoStop().
Stopped
Boolean TdjLifeCycle::Stopped inherited
Referenced by DoStop(), and Stop().
WebComponent
TdjWebComponent TdjWebComponentHolder::WebComponent
The instance of the Web Component.
WebComponentClass
TdjWebComponentClass TdjWebComponentHolder::WebComponentClass
The Web Component Class.
Referenced by GetClass(), SetContext(), and SetInitParameter().