Daraja HTTP Framework: TdjWebComponentContextHandler Class Reference
TdjWebComponentContextHandler Class Reference
Context Handler for Web Components (and Web Filters).
Public Member Functions
TdjWebComponentContextHandler (const string ContextPath, Boolean Sessions=False)
Constructor.
~TdjWebComponentContextHandler ()
Destructor.
TdjWebComponentHolder Add (TdjWebComponentClass ComponentClass, const string UrlPattern)
Add a Web Component.
TdjWebFilterHolder Add (TdjWebFilterClass FilterClass, const string UrlPattern)
Add a Web Filter, specifying a WebFilter class.
AddHandler (const IHandler Handler)
Add a handler to the container.
TdjWebComponentHolder AddWebComponent (TdjWebComponentClass ComponentClass, const string UrlPattern)
Add a Web Component.
TdjWebFilterHolder AddWebFilter (TdjWebFilterClass FilterClass, const string UrlPattern)
Add a Web Filter, specifying a WebFilter class.
string GetContextPath ()
IContext GetCurrentContext ()
The internal IContext field.
IHandler GetHandler ()
Boolean IsStarted ()
Boolean IsStopped ()
RemoveHandler (const IHandler Handler)
Removes a handler from this container.
SetErrorHandler (const IHandler Value)
SetHandler (const IHandler Value)
SetInitParameter (const string Key, const string Value)
Set initialization parameter.
SetStarted (const Boolean Value)
SetStopped (const Boolean Value)
Start ()
Starts the component.
Stop ()
Stops the component.
Public Attributes
Boolean AutoStartSession
TStrings ConnectorNames
string ContextPath
TCriticalSection CS
IHandler ErrorHandler
TStrings FConnectorNames
IContext FContext
IHandler FErrorHandler
IHandler FHandler
Boolean FStopped
IHandler Handler
Boolean Started
Boolean Stopped
TdjWebComponentHandler WebComponentHandler
Protected Member Functions
CheckStarted ()
Raises an exception if the lifecycle is in "started" state.
CheckStopped ()
Raises an exception if the lifecycle is in "stopped" state.
Boolean ContextMatches (const string ConnectorName, const string Target)
Check if the Document matches this context.
DoHandle (const string Target, TdjServerContext Context, TdjRequest Request, TdjResponse Response)
DoStart ()
Start the handler.
DoStop ()
Start the handler.
TIdHTTPSession GetSession (TdjServerContext Context, TdjRequest Request, TdjResponse Response, const Boolean Create)
Get a HTTP session.
Handle (const string Target, TdjServerContext Context, TdjRequest Request, TdjResponse Response)
Handles an HTTP request.
string ToConnectorName (TdjServerContext Context)
Creates connector name in the form 'host:port'.
Detailed Description
Context Handler for Web Components (and Web Filters).
Constructor & Destructor Documentation
TdjWebComponentContextHandler()
TdjWebComponentContextHandler::TdjWebComponentContextHandler (const string ContextPath, Boolean Sessions = False)
Constructor.
Parameters
ContextPath the context path
Sessions enable HTTP sessions
Referenced by Add(), and AddWebComponent().
~TdjWebComponentContextHandler()
TdjWebComponentContextHandler::~TdjWebComponentContextHandler ()
Destructor.
Member Function Documentation
Add() [1/2]
TdjWebComponentHolder TdjWebComponentContextHandler::Add (TdjWebComponentClass ComponentClass, const string UrlPattern)
Add a Web Component.
Parameters
ComponentClass WebComponent class
UrlPattern path specification
Returns
the Web Component holder, which can be used for further configuration.
Exceptions
EWebComponentException if the Web Component can not be added
References TdjWebComponentContextHandler(), AutoStartSession, TdjContextHandler::ContextMatches(), DoHandle(), TdjHandlerWrapper::GetSession(), and TdjContextHandler::ToConnectorName().
Add() [2/2]
TdjWebFilterHolder TdjWebComponentContextHandler::Add (TdjWebFilterClass FilterClass, const string UrlPattern)
Add a Web Filter, specifying a WebFilter class.
Parameters
FilterClass WebFilter class
UrlPattern path specification
Returns
the Web Filter holder, which can be used for further configuration.
Exceptions
Exception if the WebFilter can not be added
AddHandler()
TdjHandlerWrapper::AddHandler (const IHandler Handler) inherited
Add a handler to the container.
This implementation of AddHandler calls SetHandler with the passed handler. If this HandlerWrapper had a previous wrapped handler, then it is passed to a call to AddHandler on the passed handler.
Parameters
Handler the handler to be added
Implements IHandlerContainer.
AddWebComponent()
TdjWebComponentHolder TdjWebComponentContextHandler::AddWebComponent (TdjWebComponentClass ComponentClass, const string UrlPattern)
Add a Web Component.
Parameters
ComponentClass WebComponent class
UrlPattern path specification
Returns
the Web Component holder, which can be used for further configuration.
Exceptions
EWebComponentException if the Web Component can not be added
References TdjWebComponentContextHandler(), AddWebFilter(), and WebComponentHandler.
AddWebFilter()
TdjWebFilterHolder TdjWebComponentContextHandler::AddWebFilter (TdjWebFilterClass FilterClass, const string UrlPattern)
Add a Web Filter, specifying a WebFilter class.
Parameters
FilterClass WebFilter class
UrlPattern path specification
Returns
the Web Filter holder, which can be used for further configuration.
Exceptions
Exception if the WebFilter can not be added
Referenced by AddWebComponent().
CheckStarted()
TdjLifeCycle::CheckStarted () protected inherited
Raises an exception if the lifecycle is in "started" state.
CheckStopped()
TdjLifeCycle::CheckStopped () protected inherited
Raises an exception if the lifecycle is in "stopped" state.
References TdjLifeCycle().
ContextMatches()
Boolean TdjContextHandler::ContextMatches (const string ConnectorName, const string Target) protected inherited
Check if the Document matches this context.
Parameters
ConnectorName the connector name (like 'host:port'
Target the target URL document
Returns
True if the context matches the connector name and target URL document
Referenced by TdjWebComponentContextHandler::Add().
DoHandle()
TdjWebComponentContextHandler::DoHandle (const string Target, TdjServerContext Context, TdjRequest Request, TdjResponse Response) protected
Parameters
Target Request target
Context HTTP server context
Request HTTP request
Response HTTP response
Referenced by Add().
DoStart()
TdjContextHandler::DoStart () protected inherited
Start the handler.
See also
TdjLifeCycle
DoStop()
TdjContextHandler::DoStop () protected inherited
Start the handler.
See also
TdjLifeCycle
GetContextPath()
string TdjContextHandler::GetContextPath () inherited
GetCurrentContext()
IContext TdjContextHandler::GetCurrentContext () inherited
The internal IContext field.
GetHandler()
IHandler TdjHandlerWrapper::GetHandler () inherited
References Handler, and SetHandler().
GetSession()
TIdHTTPSession TdjHandlerWrapper::GetSession (TdjServerContext Context, TdjRequest Request, TdjResponse Response, const Boolean Create) protected inherited
Get a HTTP session.
References TdjHandlerWrapper(), FHandler, Handler, and SetHandler().
Referenced by TdjWebComponentContextHandler::Add().
Handle()
TdjWebComponentContextHandler::Handle (const string Target, TdjServerContext Context, TdjRequest Request, TdjResponse Response) protected
Handles an HTTP request.
Parameters
Target Target path or resource identifier
Context Server context for this request
Request HTTP request object
Response HTTP response object to populate
Exceptions
EWebComponentException if an exception occurs that interferes with the component's normal operation.
Implements IHandler.
IsStarted()
Boolean TdjLifeCycle::IsStarted () inherited
Returns
True if component is started
Implements ILifeCycle.
References TdjLifeCycle().
Referenced by DoStart(), and TdjWebComponentHandler::InvokeService().
IsStopped()
Boolean TdjLifeCycle::IsStopped () inherited
Returns
True if component is stopped
Implements ILifeCycle.
References Create().
Referenced by DoStart().
RemoveHandler()
TdjHandlerWrapper::RemoveHandler (const IHandler Handler) inherited
Removes a handler from this container.
Parameters
Handler Handler to remove
Implements IHandlerContainer.
SetErrorHandler()
TdjContextHandler::SetErrorHandler (const IHandler Value) inherited
SetHandler()
TdjHandlerWrapper::SetHandler (const IHandler Value) inherited
References TdjHandlerWrapper(), Create(), and Handler.
Referenced by GetHandler(), and GetSession().
SetInitParameter()
TdjContextHandler::SetInitParameter (const string Key, const string Value) inherited
Set initialization parameter.
Parameters
Key init parameter name
Value init parameter value
SetStarted()
TdjLifeCycle::SetStarted (const Boolean Value) inherited
Referenced by DoStop().
SetStopped()
TdjLifeCycle::SetStopped (const Boolean Value) inherited
Referenced by DoStop().
Start()
TdjLifeCycle::Start () inherited
Starts the component.
Implements ILifeCycle.
References TdjLifeCycle().
Referenced by DoStart().
Stop()
TdjLifeCycle::Stop () inherited
Stops the component.
Implements ILifeCycle.
References Stopped.
Referenced by DoStart(), and TdjWebComponentHandler::InvokeService().
ToConnectorName()
string TdjContextHandler::ToConnectorName (TdjServerContext Context) protected inherited
Creates connector name in the form 'host:port'.
Returns
connector name
Referenced by TdjWebComponentContextHandler::Add().
Member Data Documentation
AutoStartSession
Boolean TdjWebComponentContextHandler::AutoStartSession
Referenced by Add().
ConnectorNames
TStrings TdjContextHandler::ConnectorNames inherited
ContextPath
string TdjContextHandler::ContextPath inherited
CS
TCriticalSection TdjLifeCycle::CS inherited
Referenced by ~TdjLifeCycle().
ErrorHandler
IHandler TdjContextHandler::ErrorHandler inherited
FConnectorNames
TStrings TdjContextHandler::FConnectorNames inherited
FContext
IContext TdjContextHandler::FContext inherited
FErrorHandler
IHandler TdjContextHandler::FErrorHandler inherited
FHandler
IHandler TdjHandlerWrapper::FHandler inherited
Referenced by GetSession().
FStopped
Boolean TdjLifeCycle::FStopped inherited
Referenced by ~TdjLifeCycle(), and DoStop().
Handler
IHandler TdjHandlerWrapper::Handler inherited
Referenced by GetHandler(), GetSession(), and SetHandler().
Started
Boolean TdjLifeCycle::Started inherited
Referenced by TdjHandlerCollection::~TdjHandlerCollection(), and DoStop().
Stopped
Boolean TdjLifeCycle::Stopped inherited
Referenced by DoStop(), and Stop().
WebComponentHandler
TdjWebComponentHandler TdjWebComponentContextHandler::WebComponentHandler
Referenced by AddWebComponent().