Daraja HTTP Framework: TdjWebFilterHolder Class Reference
TdjWebFilterHolder Class Reference
A generic holder class for managing instances of TdjWebFilter.
Public Member Functions
TdjWebFilterHolder (TdjWebFilterClass WebFilterClass)
Constructor for creating an instance of TdjWebFilterHolder.
~TdjWebFilterHolder ()
DoFilter (TdjServerContext Context, TdjRequest Request, TdjResponse Response, const IWebFilterChain Chain)
Executes the filter logic for the given server context, request, and response.
TdjWebFilterClass GetClass ()
Boolean IsStarted ()
Boolean IsStopped ()
SetContext (const IContext Context)
Set the context.
SetInitParameter (const string Key, const string Value)
Set initialization parameter.
SetStarted (const Boolean Value)
SetStopped (const Boolean Value)
Start ()
Starts the component.
Stop ()
Stops the component.
Public Attributes
TCriticalSection CS
TdjWebFilterClass FClass
IWebFilterConfig FConfig
Boolean FStopped
TdjWebFilter FWebFilter
string Name
Boolean Started
Boolean Stopped
TdjWebFilter WebFilter
The instance of the filter.
TdjWebFilterClass WebFilterClass
The filter class.
Protected Member Functions
CheckStarted ()
Raises an exception if the lifecycle is in "started" state.
CheckStopped ()
Raises an exception if the lifecycle is in "stopped" state.
Detailed Description
A generic holder class for managing instances of TdjWebFilter.
This class is a specialization of TdjGenericHolder, designed to hold and manage objects of type TdjWebFilter.
Constructor & Destructor Documentation
TdjWebFilterHolder()
TdjWebFilterHolder::TdjWebFilterHolder (TdjWebFilterClass WebFilterClass)
Constructor for creating an instance of TdjWebFilterHolder.
Parameters
WebFilterClass The class reference of type TdjWebFilterClass used to initialize the web filter holder.
References SetInitParameter().
Referenced by DoFilter(), and SetInitParameter().
~TdjWebFilterHolder()
TdjWebFilterHolder::~TdjWebFilterHolder ()
Member Function Documentation
CheckStarted()
TdjLifeCycle::CheckStarted () protected inherited
Raises an exception if the lifecycle is in "started" state.
CheckStopped()
TdjLifeCycle::CheckStopped () protected inherited
Raises an exception if the lifecycle is in "stopped" state.
References TdjLifeCycle().
DoFilter()
TdjWebFilterHolder::DoFilter (TdjServerContext Context, TdjRequest Request, TdjResponse Response, const IWebFilterChain Chain)
Executes the filter logic for the given server context, request, and response.
Parameters
Context The server context in which the filter is executed.
Request The HTTP request being processed.
Response The HTTP response to be sent back to the client.
Chain The filter chain to pass control to the next filter in the chain.
Implements IWebFilter.
References TdjWebFilterHolder().
GetClass()
TdjWebFilterClass TdjWebFilterHolder::GetClass ()
References WebFilterClass.
IsStarted()
Boolean TdjLifeCycle::IsStarted () inherited
Returns
True if component is started
Implements ILifeCycle.
References TdjLifeCycle().
Referenced by DoStart(), and TdjWebComponentHandler::InvokeService().
IsStopped()
Boolean TdjLifeCycle::IsStopped () inherited
Returns
True if component is stopped
Implements ILifeCycle.
References Create().
Referenced by DoStart().
SetContext()
TdjWebFilterHolder::SetContext (const IContext Context)
Set the context.
Parameters
Context the Web Filter context
SetInitParameter()
TdjWebFilterHolder::SetInitParameter (const string Key, const string Value)
Set initialization parameter.
Parameters
Key init parameter name
Value init parameter value
References TdjWebFilterHolder().
Referenced by TdjWebFilterHolder().
SetStarted()
TdjLifeCycle::SetStarted (const Boolean Value) inherited
Referenced by DoStop().
SetStopped()
TdjLifeCycle::SetStopped (const Boolean Value) inherited
Referenced by DoStop().
Start()
TdjLifeCycle::Start () inherited
Starts the component.
Implements ILifeCycle.
References TdjLifeCycle().
Referenced by DoStart().
Stop()
TdjLifeCycle::Stop () inherited
Stops the component.
Implements ILifeCycle.
References Stopped.
Referenced by DoStart(), and TdjWebComponentHandler::InvokeService().
Member Data Documentation
CS
TCriticalSection TdjLifeCycle::CS inherited
Referenced by ~TdjLifeCycle().
FClass
TdjWebFilterClass TdjWebFilterHolder::FClass
FConfig
IWebFilterConfig TdjWebFilterHolder::FConfig
FStopped
Boolean TdjLifeCycle::FStopped inherited
Referenced by ~TdjLifeCycle(), and DoStop().
FWebFilter
TdjWebFilter TdjWebFilterHolder::FWebFilter
Name
string TdjGenericHolder::Name inherited
Started
Boolean TdjLifeCycle::Started inherited
Referenced by TdjHandlerCollection::~TdjHandlerCollection(), and DoStop().
Stopped
Boolean TdjLifeCycle::Stopped inherited
Referenced by DoStop(), and Stop().
WebFilter
TdjWebFilter TdjWebFilterHolder::WebFilter
The instance of the filter.
WebFilterClass
TdjWebFilterClass TdjWebFilterHolder::WebFilterClass
The filter class.
Referenced by GetClass().